version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestImportGitScenariosProject
  gitServerName: moaa
  gitUrl: https://github.com/Mohamed-Naufal-A-IBM
  gitUsername: Mohamed-Naufal-A-IBM
  gitBranch: main
services:
- serviceName: project.testimportgitscenarios.integrations:test
  packages:
  - name: TestImportGitScenariosProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
- serviceName: project.testimportgitscenarios.integrations:testFlowService_123
  packages:
  - name: TestImportGitScenariosProject
    version: "1.0"
