version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestImportGitScenariosProject
  gitServerName: moaa
  gitUrl: https://github.com/Mohamed-Naufal-A-IBM
  gitUsername: Mohamed-Naufal-A-IBM
  gitBranch: main
services:
- serviceName: project.testimportgitscenarios.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:test
  packages:
  - name: TestImportGitScenariosProject
    version: "1.0"
- serviceName: project.testimportgitscenarios.documenttypes:test
  packages:
  - name: TestImportGitScenariosProject
    version: "1.0"
- serviceName: project.testimportgitscenarios.integrations:test
  packages:
  - name: TestImportGitScenariosProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
- serviceName: project.testimportgitscenarios.integrations:test1
  packages:
  - name: TestImportGitScenariosProject
    version: "1.0"
- serviceName: project.testimportgitscenarios.integrations:test12
  packages:
  - name: TestImportGitScenariosProject
    version: "1.0"
- serviceName: project.testimportgitscenarios.integrations:testFlow
  packages:
  - name: TestImportGitScenariosProject
    version: "1.0"
- serviceName: project.testimportgitscenarios.integrations:testFlow_imported
  packages:
  - name: TestImportGitScenariosProject
    version: "1.0"
- serviceName: project.test.integrations:flow_1_imported
  packages:
  - name: TestImportGitScenariosProject
    version: "1.0"
- serviceName: project.test.integrations:flow_2_imported
  packages:
  - name: TestImportGitScenariosProject
    version: "1.0"
- serviceName: pub.string:length
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
- serviceName: project.testimportgitscenarios.integrations:testFlowService_12
  packages:
  - name: TestImportGitScenariosProject
    version: "1.0"
- serviceName: pub.json:documentToJSONString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
- serviceName: project.testimportgitscenarios.referencedata:test
  packages:
  - name: TestImportGitScenariosProject
    version: "1.0"
- serviceName: project.testimportgitscenarios.integrations:testFlowService_123
  packages:
  - name: TestImportGitScenariosProject
    version: "1.0"
- serviceName: project.testimportgitscenarios.integrations:testDummyFlow
  packages:
  - name: TestImportGitScenariosProject
    version: "1.0"
