version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestImportGitScenariosProject
  gitServerName: moaa
  gitUrl: https://github.com/Mohamed-Naufal-A-IBM
  gitUsername: Mohamed-Naufal-A-IBM
  gitBranch: main
services:
- serviceName: project.testimportgitscenarios.integrations:test
  packages:
  - name: TestImportGitScenariosProject
    version: "1.0"
